services:
  # Development services
  postgres:
    image: postgres:16.3
    ports:
      - "8090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ompec_schedule_backend
      POSTGRES_PASSWORD: "S6y5fjtxDOJWY272yE5vbI3Et42CWEPE"
    volumes:
      - ompec_schedule_backend_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    ports:
      - "8091:6379"
    command: redis-server --requirepass "X_jkEz_2QOh3NdOlMXljLnjKsZl5_5JV"
    environment:
      - REDIS_REPLICATION_MODE=master

  # Test services
  postgres_test:
    image: postgres:16.3
    ports:
      - "9090:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: ompec_schedule_backend_test
      POSTGRES_PASSWORD: "Tf_Ew_WKm4MTenPd7OwQopx430h8-FBY"
    volumes:
      - ompec_schedule_backend_test_data:/var/lib/postgresql/data

  redis_test:
    image: redis:6.2.6
    ports:
      - "9091:6379"
    command: redis-server --requirepass "dQFZKozWav0X-OI2Z3wl-fwHt5BwJ-5d"
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  ompec_schedule_backend_data:
  ompec_schedule_backend_test_data:
